<a href="https://colab.research.google.com/github/Sherry66410/ML-PROJECT/blob/main/Copy_of_Day2_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
df=sns.load_dataset("titanic")

In [ ]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df.shape

(891, 15)

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [ ]:
df.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df=df.drop(columns=['deck'])
df.shape

(891, 14)

In [ ]:
df.dropna(subset=['embarked','embark_town'],inplace=True)
print(df.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
embark_town      0
alive            0
alone            0
dtype: int64

In [ ]:
age_mean=df['age'].mean()
df['age']=df['age'].fillna(age_mean)

In [ ]:
#creating new column titled as age_group
df['age_group']=np.where(df['age']<18,"Child","Adult")
#creating new column titled as fare_per_person
df['family_size']=df['sibsp']+df['parch']
df['fare_per_person']=df['fare']/(df['family_size']+1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   survived         889 non-null    int64
 1   pclass           889 non-null    int64
 2   sex              889 non-null    object
 3   age              889 non-null    float64
 4   sibsp            889 non-null    int64
 5   parch            889 non-null    int64
 6   fare             889 non-null    float64
 7   embarked         889 non-null    object
 8   class            889 non-null    category
 9   who              889 non-null    object
 10  adult_male       889 non-null    bool
 11  embark_town      889 non-null    object
 12  alive            889 non-null    object
 13  alone            889 non-null    bool
 14  age_group        889 non-null    object
 15  family_size      889 non-null    int64
 16  fare_per_person  889 non-null    float64
dtypes: bool(2), category(1), float64(3), int64(5), object(6)
memory usage: 106.9+ KB

In [ ]:
#renaming a column
df.rename(columns={'pclass':'Passenger_Class'},inplace=True)
df

,survived,Passenger_Class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_person
0,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,Southampton,no,False,Adult,1,3.62500
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.64165
2,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,Southampton,yes,True,Adult,0,7.92500
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.55000
4,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,Southampton,no,True,Adult,0,8.05000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,Southampton,no,True,Adult,0,13.00000
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True,Adult,0,30.00000
888,0,3,female,29.642093,1,2,23.4500,S,Third,woman,False,Southampton,no,False,Adult,3,5.86250
889,1,1,male,26.000000,0,0,30.0000,C,First,man,True,Cherbourg,yes,True,Adult,0,30.00000
890,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,Queenstown,no,True,Adult,0,7.75000

In [ ]:
#filtering and conditioning
df[df['age']>df['age'].mean()]

,survived,Passenger_Class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_person
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.641650
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.550000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True,Adult,0,8.050000
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,Southampton,no,True,Adult,0,51.862500
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,Southampton,yes,True,Adult,0,26.550000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,Southampton,no,True,Adult,0,9.000000
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,Cherbourg,yes,False,Adult,1,41.579150
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,Southampton,no,True,Adult,0,7.895800
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,Queenstown,no,False,Adult,5,4.854167
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,Queenstown,no,True,Adult,0,7.750000

In [ ]:
df[(df['sex']=='female')&(df['Passenger_Class']==1)]

,survived,Passenger_Class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_person
1,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.641650
3,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.550000
11,1,1,female,58.000000,0,0,26.5500,S,First,woman,False,Southampton,yes,True,Adult,0,26.550000
31,1,1,female,29.642093,1,0,146.5208,C,First,woman,False,Cherbourg,yes,False,Adult,1,73.260400
52,1,1,female,49.000000,1,0,76.7292,C,First,woman,False,Cherbourg,yes,False,Adult,1,38.364600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.000000,1,1,164.8667,S,First,woman,False,Southampton,yes,False,Adult,2,54.955567
862,1,1,female,48.000000,0,0,25.9292,S,First,woman,False,Southampton,yes,True,Adult,0,25.929200
871,1,1,female,47.000000,1,1,52.5542,S,First,woman,False,Southampton,yes,False,Adult,2,17.518067
879,1,1,female,56.000000,0,1,83.1583,C,First,woman,False,Cherbourg,yes,False,Adult,1,41.579150
887,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,Southampton,yes,True,Adult,0,30.000000

In [ ]:
df[df['survived']==1]

,survived,Passenger_Class,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone,age_group,family_size,fare_per_person
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False,Adult,1,35.64165
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True,Adult,0,7.92500
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False,Adult,1,26.55000
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,Southampton,yes,False,Adult,2,3.71110
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,Cherbourg,yes,False,Child,1,15.03540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,Cherbourg,yes,True,Child,0,7.22500
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,Cherbourg,yes,False,Adult,1,41.57915
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,Southampton,yes,False,Adult,1,13.00000
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,Southampton,yes,True,Adult,0,30.00000
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,Cherbourg,yes,True,Adult,0,30.00000

In [ ]:
#survival rate by gendder
df.groupby('sex')['survived'].mean()

sex
female    0.740385
male      0.188908
Name: survived, dtype: float64

In [ ]:
#avg fare by class
df.groupby('class')['fare'].mean()

/tmp/ipython-input-3869503639.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('class')['fare'].mean()

class
First     84.193516
Second    20.662183
Third     13.675550
Name: fare, dtype: float64

In [ ]:
#correlation
df.corr(numeric_only=True)

,survived,Passenger_Class,age,sibsp,parch,fare,adult_male,alone,family_size,fare_per_person
survived,1.000000,-0.335549,-0.074513,-0.034040,0.083151,0.255290,-0.555520,-0.206207,0.018277,0.217902
Passenger_Class,-0.335549,1.000000,-0.328256,0.081656,0.016824,-0.548193,0.090098,0.138553,0.064221,-0.482024
age,-0.074513,-0.328256,1.000000,-0.231908,-0.178013,0.088780,0.258793,0.177445,-0.247459,0.136787
sibsp,-0.034040,0.081656,-0.231908,1.000000,0.414542,0.160887,-0.255401,-0.584186,0.890654,-0.093211
parch,0.083151,0.016824,-0.178013,0.414542,1.000000,0.217532,-0.351945,-0.583112,0.782988,-0.067422
fare,0.255290,-0.548193,0.088780,0.160887,0.217532,1.000000,-0.179851,-0.274079,0.218658,0.840902
adult_male,-0.555520,0.090098,0.258793,-0.255401,-0.351945,-0.179851,1.000000,0.407992,-0.350419,-0.078503
alone,-0.206207,0.138553,0.177445,-0.584186,-0.583112,-0.274079,0.407992,1.000000,-0.690654,0.042706
family_size,0.018277,0.064221,-0.247459,0.890654,0.782988,0.218658,-0.350419,-0.690654,1.000000,-0.097399
fare_per_person,0.217902,-0.482024,0.136787,-0.093211,-0.067422,0.840902,-0.078503,0.042706,-0.097399,1.000000

In [ ]:
##TIPS
df=sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df.shape

(244, 7)

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [ ]:
df.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
#5)
df_bill=df['total_bill'].mean()
df_bill

np.float64(19.78594262295082)

In [ ]:
#6)
df_tip=df['tip'].mean()
df_tip

np.float64(2.99827868852459)

In [ ]:
#7)
df_med=df['tip'].median()
df_med

2.9

In [ ]:
#9)
df['tip_per']=(df['tip']*100)/(df['total_bill'])
df

     total_bill   tip     sex smoker   day    time  size    tip_per
0         16.99  1.01  Female     No   Sun  Dinner     2   5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3  16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3  16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2  13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4  14.680765
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3  20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2   7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2   8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2   9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2  15.974441

[244 rows x 8 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
 7   tip_per     244 non-null    float64
dtypes: category(4), float64(3), int64(1)
memory usage: 9.3 KB

In [ ]:
#10)
df['high_spender']=np.where(df['total_bill']>df['total_bill'].mean(),"1","0")
df['high_spender']

0      0
1      0
2      1
3      1
4      1
      ..
239    1
240    1
241    1
242    0
243    0
Name: high_spender, Length: 244, dtype: object

In [ ]:
#11
df['total_bill']>30

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df[df['tip_per']>20]

,total_bill,tip,sex,smoker,day,time,size,tip_per,high_spender
6,8.77,2.00,Male,No,Sun,Dinner,2,22.805017,0
9,14.78,3.23,Male,No,Sun,Dinner,2,21.853857,0
14,14.83,3.02,Female,No,Sun,Dinner,2,20.364127,0
17,16.29,3.71,Male,No,Sun,Dinner,3,22.774708,0
18,16.97,3.50,Female,No,Sun,Dinner,3,20.624632,0
20,17.92,4.08,Male,No,Sat,Dinner,2,22.767857,0
42,13.94,3.06,Male,No,Sun,Dinner,2,21.951220,0
46,22.23,5.00,Male,No,Sun,Dinner,2,22.492128,1
51,10.29,2.60,Female,No,Sun,Dinner,2,25.267250,0
63,18.29,3.76,Male,Yes,Sat,Dinner,4,20.557682,0
67,3.07,1.00,Female,Yes,Sat,Dinner,1,32.573290,0
81,16.66,3.40,Male,No,Thur,Lunch,2,20.408163,0
87,18.28,4.00,Male,No,Thur,Lunch,2,21.881838,0
88,24.71,5.85,Male,No,Thur,Lunch,2,23.674626,1
93,16.32,4.30,Female,Yes,Fri,Dinner,2,26.348039,0
100,11.35,2.50,Female,Yes,Fri,Dinner,2,22.026432,0
108,18.24,3.76,Male,No,Sat,Dinner,2,20.614035,0
109,14.31,4.00,Female,Yes,Sat,Dinner,2,27.952481,0
110,14.00,3.00,Male,No,Sat,Dinner,2,21.428571,0
115,17.31,3.50,Female,No,Sun,Dinner,2,20.219526,0
124,12.48,2.52,Female,No,Thur,Lunch,2,20.192308,0
139,13.16,2.75,Female,No,Thur,Lunch,2,20.896657,0
140,17.47,3.50,Female,No,Thur,Lunch,2,20.034345,0
149,7.51,2.00,Male,No,Thur,Lunch,2,26.631158,0
172,7.25,5.15,Male,Yes,Sun,Dinner,2,71.034483,0
174,16.82,4.00,Male,Yes,Sun,Dinner,2,23.781213,0
178,9.60,4.00,Female,Yes,Sun,Dinner,2,41.666667,0
181,23.33,5.65,Male,Yes,Sun,Dinner,2,24.217745,1
183,23.17,6.50,Male,Yes,Sun,Dinner,4,28.053517,1
185,20.69,5.00,Male,No,Sun,Dinner,5,24.166264,1
191,19.81,4.19,Female,Yes,Thur,Lunch,2,21.150934,1
194,16.58,4.00,Male,Yes,Thur,Lunch,2,24.125452,0
200,18.71,4.00,Male,Yes,Thur,Lunch,3,21.378942,0
214,28.17,6.50,Female,Yes,Sat,Dinner,3,23.074192,1
221,13.42,3.48,Female,Yes,Fri,Lunch,2,25.931446,0
222,8.58,1.92,Male,Yes,Fri,Lunch,1,22.377622,0
228,13.28,2.72,Male,No,Sat,Dinner,2,20.481928,0
232,11.61,3.39,Male,No,Sat,Dinner,2,29.198966,0
239,29.03,5.92,Male,No,Sat,Dinner,3,20.392697,1

In [ ]:
#13)

df_gen=df.groupby('sex')['tip'].mean()
df_gen

/tmp/ipython-input-1799582.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_gen=df.groupby('sex')['tip'].mean()

sex
Male      3.089618
Female    2.833448
Name: tip, dtype: float64

In [ ]:
#14)
df_d=df.groupby('day')['total_bill'].mean()
df_d

/tmp/ipython-input-1404288251.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_d=df.groupby('day')['total_bill'].mean()

day
Thur    17.682742
Fri     17.151579
Sat     20.441379
Sun     21.410000
Name: total_bill, dtype: float64

In [ ]:
#15)
df_s=df.groupby('smoker')['tip_per'].mean()
df_s

/tmp/ipython-input-3554716318.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_s=df.groupby('smoker')['tip_per'].mean()

smoker
Yes    16.319604
No     15.932846
Name: tip_per, dtype: float64

In [ ]:
#16)
df.corr(numeric_only=True)

            total_bill       tip      size   tip_per
total_bill    1.000000  0.675734  0.598315 -0.338624
tip           0.675734  1.000000  0.489299  0.342370
size          0.598315  0.489299  1.000000 -0.142860
tip_per      -0.338624  0.342370 -0.142860  1.000000

In [ ]:
#numpy
array=np.arange(1,17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
y=np.array([1,2,3,4,5,6])
y

array([1, 2, 3, 4, 5, 6])

In [ ]:
y[y%2==0]=-1
y

array([ 1, -1,  3, -1,  5, -1])

In [ ]:
arr1=np.array([10,20,30,40,50])
arr1
np.mean(arr1)

np.float64(30.0)

In [ ]:
np.std(arr1)

np.float64(14.142135623730951)

In [ ]:
norm=(arr1-np.mean(arr1))/np.std(arr1)
norm

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [ ]:
y=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
y[0][1]

np.int64(2)

In [ ]:
y[1][1]

np.int64(5)

In [ ]:
y[2][0]

np.int64(7)

In [ ]:
y[2:]

array([[7, 8, 9]])

In [ ]:
y[1:,:2]

array([[4, 5],
       [7, 8]])

In [ ]:
y[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#penguin
df=sns.load_dataset("penguins")
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [ ]:
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [ ]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
df.shape

(344, 7)

In [ ]:
df.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df.dtypes

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

In [ ]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [ ]:
len_mean=df['bill_length_mm'].mean()
len_mean

np.float64(43.9219298245614)

In [ ]:
df['bill_length_mm']=df['bill_length_mm'].fillna(len_mean)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
depth_mean=df['bill_depth_mm'].mean()
depth_mean
df['bill_depth_mm']=df['bill_depth_mm'].fillna(depth_mean)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
depth_mean=df['bill_depth_mm'].mean()
depth_mean

np.float64(17.151169590643274)

In [ ]:
flipper_length=df['flipper_length_mm'].mean()
flipper_length

np.float64(200.91520467836258)

In [ ]:
df['flipper_length_mm']=df['flipper_length_mm'].fillna(flipper_length)
df['flipper_length_mm']

0      181.000000
1      186.000000
2      195.000000
3      200.915205
4      193.000000
          ...
339    200.915205
340    215.000000
341    222.000000
342    212.000000
343    213.000000
Name: flipper_length_mm, Length: 344, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
mass_mean=df['body_mass_g'].mean()
mass_mean

np.float64(4201.754385964912)

In [ ]:
df['body_mass_g']=df['body_mass_g'].fillna(mass_mean)
df['body_mass_g']

0      3750.000000
1      3800.000000
2      3250.000000
3      4201.754386
4      3450.000000
          ...
339    4201.754386
340    4850.000000
341    5750.000000
342    5200.000000
343    5400.000000
Name: body_mass_g, Length: 344, dtype: float64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
df['bill_length_mm']>43

0      False
1      False
2      False
3       True
4      False
       ...
339     True
340     True
341     True
342     True
343     True
Name: bill_length_mm, Length: 344, dtype: bool

In [ ]:
[df['bill_length_mm']>43]

[0      False
 1      False
 2      False
 3       True
 4      False
        ...
 339     True
 340     True
 341     True
 342     True
 343     True
 Name: bill_length_mm, Length: 344, dtype: bool]

In [ ]:
df[(df['sex']=='male')&(df['bill_length_mm']>43)]
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,Male
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,Female
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,Female
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,NaN
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,43.92193,17.15117,200.915205,4201.754386,NaN
340,Gentoo,Biscoe,46.80000,14.30000,215.000000,4850.000000,Female
341,Gentoo,Biscoe,50.40000,15.70000,222.000000,5750.000000,Male
342,Gentoo,Biscoe,45.20000,14.80000,212.000000,5200.000000,Female
343,Gentoo,Biscoe,49.90000,16.10000,213.000000,5400.000000,Male

In [ ]:
df['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [ ]:
df_s=df.groupby('species')['bill_length_mm'].mean()
df_s

species
Adelie       38.791391
Chinstrap    48.833824
Gentoo       47.504878
Name: bill_length_mm, dtype: float64

In [ ]:
[df['sex']=='Male':"0","1"]

[0       True
 1      False
 2      False
 3      False
 4      False
        ...
 339    False
 340    False
 341     True
 342    False
 343     True
 Name: sex, Length: 344, dtype: bool,
 '0',
 '1']

In [16]:
df['ratio']=df['bill_length_mm']/df['bill_depth_mm']
df['ratio']

0      2.090909
1      2.270115
2      2.238889
3           NaN
4      1.901554
         ...
339         NaN
340    3.272727
341    3.210191
342    3.054054
343    3.099379
Name: ratio, Length: 344, dtype: float64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
 7   ratio              342 non-null    float64
dtypes: float64(5), object(3)
memory usage: 21.6+ KB

In [18]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,2.238889
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,1.901554
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,3.272727
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,3.210191
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,3.054054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,3.099379

In [19]:
df['ratio']=np.where(df['ratio']>df['ratio'].mean(),"1","0")
df['ratio']

0      0
1      0
2      0
3      0
4      0
      ..
339    0
340    1
341    1
342    1
343    1
Name: ratio, Length: 344, dtype: object

In [20]:
df=df.corr(numeric_only=True)
df

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
bill_length_mm,1.000000,-0.235053,0.656181,0.595110
bill_depth_mm,-0.235053,1.000000,-0.583851,-0.471916
flipper_length_mm,0.656181,-0.583851,1.000000,0.871202
body_mass_g,0.595110,-0.471916,0.871202,1.000000